Repository sharetreats-team/chatbot-treats-webhook, pull requests merged in 2023-07, with the labels that each got.

#83 토큰 저장소 레디스로 변경 및 유효시간 만료 메시지 보내는 클래스 작성
  .github/workflows/deploy.yml
  src/main/java/com/sharetreats/chatbot/infra/config/RedisConfig.java
  src/main/java/com/sharetreats/chatbot/infra/config/TokenConfig.java
  src/main/java/com/sharetreats/chatbot/module/controller/WebhookController.java
  src/main/java/com/sharetreats/chatbot/module/controller/webhook/SendInvalidTokenMessage.java
  src/main/resources/application.yaml
Labels: enhancement

#87 update: 결제 내역 및 show treats 메시지 디자인 수정
  src/main/java/com/sharetreats/chatbot/module/controller/dto/paymentDtos/PayResultButtons.java
  src/main/java/com/sharetreats/chatbot/module/controller/dto/paymentDtos/PaymentFailedMessage.java
  src/main/java/com/sharetreats/chatbot/module/controller/dto/welcomeDtos/WelcomeButton.java
Labels: enhancement, update

#97 [refactor] textService, RichMediaService - 기능에 따라 서비스를 분리함
  src/main/java/com/sharetreats/chatbot/module/controller/WebhookController.java
  src/main/java/com/sharetreats/chatbot/module/controller/webhook/SendProductDetail.java
  src/main/java/com/sharetreats/chatbot/module/controller/webhook/SendProductListByBrand.java
  src/main/java/com/sharetreats/chatbot/module/controller/webhook/SendPurchaseInfo.java
  src/main/java/com/sharetreats/chatbot/module/service/DiscountService.java
  src/main/java/com/sharetreats/chatbot/module/service/DiscountServiceImpl.java
  src/main/java/com/sharetreats/chatbot/module/service/KeyboardService.java
  src/main/java/com/sharetreats/chatbot/module/service/ProductDetailService.java
  src/main/java/com/sharetreats/chatbot/module/service/ProductDetailServiceImpl.java
  src/main/java/com/sharetreats/chatbot/module/service/ProductListService.java
  src/main/java/com/sharetreats/chatbot/module/service/ProductListServiceImpl.java
  src/main/java/com/sharetreats/chatbot/module/service/PurchaseInfoService.java
  src/main/java/com/sharetreats/chatbot/module/service/PurchaseInfoServiceImpl.java
  src/main/java/com/sharetreats/chatbot/module/service/TextService.java
Labels: refactor

#100 [refactor] product - brand 연결관계 수립에 따른 관련 코드 수정
  src/main/java/com/sharetreats/chatbot/module/controller/dto/paymentDtos/PayResultButtons.java
  src/main/java/com/sharetreats/chatbot/module/entity/Product.java
  src/main/java/com/sharetreats/chatbot/module/repository/ProductRepository.java
  src/main/java/com/sharetreats/chatbot/module/service/ProductDetailServiceImpl.java
  src/main/java/com/sharetreats/chatbot/module/service/ProductListServiceImpl.java
Labels: refactor

#102 product 초기 데이터 브랜드 id 정보 수정 및 포인트 충전 금액 증가
  src/main/java/com/sharetreats/chatbot/module/service/AccountService.java
  src/main/resources/db/product-data.sql
Labels: update

#105 [update] 상품 상세정보, 구매정보 문구 수정
  src/main/java/com/sharetreats/chatbot/module/service/ProductDetailServiceImpl.java
  src/main/java/com/sharetreats/chatbot/module/service/PurchaseInfoServiceImpl.java
Labels: refactor
